call emcc ^
    -I../src/game -I../src -I../ -I../build/us/include -I../build/us/ -I../include ^
    -DNON_MATCHING=1 -DAVOID_UB -DVERSION_US=1 ^
    -g4 -o bin.o ^
    ../bin/cave.c ^
    ../bin/debug_level_select.c ^
    ../bin/effect.c ^
    ../bin/generic.c ^
    ../bin/grass.c ^
    ../bin/machine.c ^
    ../bin/mountain.c ^
    ../bin/fire.c ^
    ../bin/inside.c ^
    ../bin/outside.c ^
    ../bin/segment2.c ^
    ../bin/sky.c ^
    ../bin/snow.c ^
    ../bin/spooky.c ^
    ../bin/title_screen_bg.c ^
    ../bin/water.c

call emcc ^
    -I../src/game -I../src -I../ -I../build/us/include -I../build/us/ -I../include ^
    -DNON_MATCHING=1 -DAVOID_UB -DVERSION_US=1 ^
    -g4 -o actors.o ^
    ../actors/common0.c ^
    ../actors/common0_geo.c ^
    ../actors/common1.c ^
    ../actors/common1_geo.c ^
    ../actors/group0.c ^
    ../actors/group0_geo.c ^
    ../actors/group1.c ^
    ../actors/group1_geo.c ^
    ../actors/group2.c ^
    ../actors/group2_geo.c ^
    ../actors/group3.c ^
    ../actors/group3_geo.c ^
    ../actors/group4.c ^
    ../actors/group4_geo.c ^
    ../actors/group5.c ^
    ../actors/group5_geo.c ^
    ../actors/group6.c ^
    ../actors/group6_geo.c ^
    ../actors/group7.c ^
    ../actors/group7_geo.c ^
    ../actors/group8.c ^
    ../actors/group8_geo.c ^
    ../actors/group9.c ^
    ../actors/group9_geo.c ^
    ../actors/group10.c ^
    ../actors/group10_geo.c ^
    ../actors/group11.c ^
    ../actors/group11_geo.c ^
    ../actors/group12.c ^
    ../actors/group12_geo.c ^
    ../actors/group13.c ^
    ../actors/group13_geo.c ^
    ../actors/group14.c ^
    ../actors/group14_geo.c ^
    ../actors/group15.c ^
    ../actors/group15_geo.c ^
    ../actors/group16.c ^
    ../actors/group16_geo.c ^
    ../actors/group17.c ^
    ../actors/group17_geo.c

call emcc ^
    -I../src/game -I../src -I../ -I../build/us/include -I../build/us/ -I../include ^
    -DNON_MATCHING=1 -DAVOID_UB -DVERSION_US=1 ^
    -g4 -o levels.o ^
    ../levels/entry.c ^
    ../levels/scripts.c ^
    ../levels/bbh/geo.c ^
    ../levels/bbh/leveldata.c ^
    ../levels/bbh/script.c ^
    ../levels/bitdw/geo.c ^
    ../levels/bitdw/leveldata.c ^
    ../levels/bitdw/script.c ^
    ../levels/bitfs/geo.c ^
    ../levels/bitfs/leveldata.c ^
    ../levels/bitfs/script.c ^
    ../levels/bits/geo.c ^
    ../levels/bits/leveldata.c ^
    ../levels/bits/script.c ^
    ../levels/bob/geo.c ^
    ../levels/bob/leveldata.c ^
    ../levels/bob/script.c ^
    ../levels/bowser_1/geo.c ^
    ../levels/bowser_1/leveldata.c ^
    ../levels/bowser_1/script.c ^
    ../levels/bowser_2/geo.c ^
    ../levels/bowser_2/leveldata.c ^
    ../levels/bowser_2/script.c ^
    ../levels/bowser_3/geo.c ^
    ../levels/bowser_3/leveldata.c ^
    ../levels/bowser_3/script.c ^
    ../levels/castle_courtyard/geo.c ^
    ../levels/castle_courtyard/leveldata.c ^
    ../levels/castle_courtyard/script.c ^
    ../levels/castle_grounds/geo.c ^
    ../levels/castle_grounds/leveldata.c ^
    ../levels/castle_grounds/script.c ^
    ../levels/castle_inside/geo.c ^
    ../levels/castle_inside/leveldata.c ^
    ../levels/castle_inside/script.c ^
    ../levels/ccm/geo.c ^
    ../levels/ccm/leveldata.c ^
    ../levels/ccm/script.c ^
    ../levels/cotmc/geo.c ^
    ../levels/cotmc/leveldata.c ^
    ../levels/cotmc/script.c ^
    ../levels/ddd/geo.c ^
    ../levels/ddd/leveldata.c ^
    ../levels/ddd/script.c ^
    ../levels/ending/geo.c ^
    ../levels/ending/leveldata.c ^
    ../levels/ending/script.c ^
    ../levels/hmc/geo.c ^
    ../levels/hmc/leveldata.c ^
    ../levels/hmc/script.c ^
    ../levels/intro/geo.c ^
    ../levels/intro/leveldata.c ^
    ../levels/intro/script.c ^
    ../levels/jrb/geo.c ^
    ../levels/jrb/leveldata.c ^
    ../levels/jrb/script.c ^
    ../levels/lll/geo.c ^
    ../levels/lll/leveldata.c ^
    ../levels/lll/script.c ^
    ../levels/menu/geo.c ^
    ../levels/menu/leveldata.c ^
    ../levels/menu/script.c ^
    ../levels/pss/geo.c ^
    ../levels/pss/leveldata.c ^
    ../levels/pss/script.c ^
    ../levels/rr/geo.c ^
    ../levels/rr/leveldata.c ^
    ../levels/rr/script.c ^
    ../levels/sa/geo.c ^
    ../levels/sa/leveldata.c ^
    ../levels/sa/script.c ^
    ../levels/sl/geo.c ^
    ../levels/sl/leveldata.c ^
    ../levels/sl/script.c ^
    ../levels/ssl/geo.c ^
    ../levels/ssl/leveldata.c ^
    ../levels/ssl/script.c ^
    ../levels/thi/geo.c ^
    ../levels/thi/leveldata.c ^
    ../levels/thi/script.c ^
    ../levels/totwc/geo.c ^
    ../levels/totwc/leveldata.c ^
    ../levels/totwc/script.c ^
    ../levels/ttc/geo.c ^
    ../levels/ttc/leveldata.c ^
    ../levels/ttc/script.c ^
    ../levels/ttm/geo.c ^
    ../levels/ttm/leveldata.c ^
    ../levels/ttm/script.c ^
    ../levels/vcutm/geo.c ^
    ../levels/vcutm/leveldata.c ^
    ../levels/vcutm/script.c ^
    ../levels/wdw/geo.c ^
    ../levels/wdw/leveldata.c ^
    ../levels/wdw/script.c ^
    ../levels/wf/geo.c ^
    ../levels/wf/leveldata.c ^
    ../levels/wf/script.c ^
    ../levels/wmotr/geo.c ^
    ../levels/wmotr/leveldata.c ^
    ../levels/wmotr/script.c

call emcc ^
    -I../src/game -I../src -I../ -I../build/us/include -I../build/us/ -I../include ^
    -DNON_MATCHING=1 -DAVOID_UB -DVERSION_US=1 ^
    -g4 -o sm64.o ^
    emscripten_main.cpp ^
    ../data/behavior_data.c ^
    ../src/audio/data.c ^
    ../src/audio/external.c ^
    ../src/audio/load.c ^
    ../src/audio/memory.c ^
    ../src/audio/playback.c ^
    ../src/audio/seqplayer.c ^
    ../src/audio/synthesis.c ^
    ../src/engine/math_util.c ^
    ../src/game/area.c ^
    ../src/game/behavior_actions.c ^
    ../src/game/camera.c ^
    ../src/game/display.c ^
    ../src/game/game.c ^
    ../src/game/ingame_menu.c ^
    ../src/game/level_update.c ^
    ../src/game/main.c ^
    ../src/game/obj_behaviors_2.c ^
    ../src/game/object_list_processor.c ^
    ../src/game/paintings.c ^
    ../src/game/rendering_graph_node.c ^
    ../src/game/save_file.c ^
    ../src/engine/geo_layout.c ^
    ../src/game/memory.c ^
    ../src/buffers/buffers.c ^
    ../src/game/moving_texture.c ^
    ../src/game/object_helpers.c ^
    ../src/engine/graph_node.c ^
    ../src/game/sound_init.c ^
    ../src/game/debug.c ^
    ../src/game/obj_behaviors.c ^
    ../src/game/interaction.c ^
    ../src/game/debug_course.c ^
    ../src/game/envfx_bubbles.c ^
    ../src/game/print.c ^
    ../src/game/platform_displacement.c ^
    ../src/engine/surface_collision.c ^
    ../src/game/spawn_sound.c ^
    ../src/menu/intro_geo.c ^
    ../src/engine/behavior_script.c ^
    ../src/engine/surface_load.c ^
    ../src/menu/star_select.c ^
    ../src/game/mario_misc.c ^
    ../src/game/mario_step.c ^
    ../src/game/hud.c ^
    ../src/game/geo_misc.c ^
    ../src/game/mario.c ^
    ../src/game/mario_actions_airborne.c ^
    ../src/game/mario_actions_automatic.c ^
    ../src/game/mario_actions_cutscene.c ^
    ../src/game/mario_actions_moving.c ^
    ../src/game/mario_actions_object.c ^
    ../src/game/mario_actions_stationary.c ^
    ../src/game/mario_actions_submerged.c ^
    ../src/game/macro_special_objects.c ^
    ../src/game/screen_transition.c ^
    ../src/game/object_collision.c ^
    ../src/goddard/renderer.c ^
    ../src/goddard/gd_main.c ^
    ../src/goddard/debug_utils.c ^
    ../src/goddard/draw_objects.c ^
    ../src/goddard/objects.c ^
    ../src/goddard/dynlist_proc.c ^
    ../src/goddard/shape_helper.c ^
    ../src/goddard/gd_math.c ^
    ../src/goddard/gd_memory.c ^
    ../src/goddard/skin.c ^
    ../src/menu/file_select.c ^
    ../src/goddard/old_menu.c ^
    ../src/game/level_geo.c ^
    ../src/goddard/joints.c ^
    ../src/game/spawn_object.c ^
    ../src/goddard/skin_movement.c ^
    ../src/goddard/sfx.c ^
    ../src/game/skybox.c ^
    ../src/game/envfx_snow.c ^
    ../lib/src/guPerspectiveF.c ^
    ../src/buffers/zbuffer.c ^
    ../src/buffers/framebuffers.c ^
    ../src/buffers/gfx_output_buffer.c ^
    ../lib/src/guTranslateF.c ^
    ../src/game/profiler.c ^
    ../src/goddard/particles.c ^
    ../lib/src/guOrthoF.c ^
    ../lib/src/guMtxF2L.c ^
    ../lib/src/guRotateF.c ^
    ../src/engine/level_script.c ^
    ../lib/src/osAiSetFrequency.c ^
    ../lib/src/osEepromLongRead.c ^
    ../lib/src/osGetTime.c ^
    ../lib/src/osInitialize.c ^
    ../lib/src/osContInit.c ^
    ../src/goddard/dynlists/dynlist_unused.c ^
    ../src/game/shadow.c ^
    ../src/goddard/dynlists/dynlist_mario_master.c ^
    ../src/goddard/dynlists/dynlists_mario_eyebrows_mustache.c ^
    ../lib/src/osContStartReadData.c ^
    ../lib/src/osTimer.c ^
    ../src/goddard/dynlists/dynlist_mario_face.c ^
    ../src/goddard/dynlists/dynlists_mario_eyes.c ^
    ../src/goddard/dynlists/anim_group_1.c ^
    ../src/goddard/dynlists/anim_group_2.c ^
    ../src/goddard/dynlists/dynlist_test_cube.c ^
    ../src/goddard/dynlists/anim_mario_mustache_right.c ^
    ../src/goddard/dynlists/anim_mario_mustache_left.c ^
    ../src/goddard/dynlists/anim_mario_eyebrows_1.c ^
    ../src/goddard/dynlists/anim_mario_lips_1.c ^
    ../src/goddard/dynlists/anim_mario_lips_2.c ^
    ../src/engine/graph_node_manager.c ^
    ../lib/src/guNormalize.c ^
    ../lib/src/guScaleF.c ^
    ../lib/src/osViSwapBuffer.c ^
    ../lib/src/__osViInit.c ^
    ../lib/src/osPiStartDma.c ^
    ../lib/src/osViSetSpecialFeatures.c ^
    ../lib/src/osEepromLongWrite.c ^
    ../lib/src/osEepromProbe.c ^
    ../lib/src/osViBlack.c ^
    ../lib/src/osSendMesg.c ^
    ../lib/src/osEepromRead.c ^
    ../lib/src/osRecvMesg.c ^
    ../lib/src/osCreatePiManager.c ^
    ../lib/src/osEepromWrite.c ^
    ../lib/src/__osDequeueThread.c ^
    ../lib/src/osStartThread.c ^
    ../lib/src/osCreateMesgQueue.c ^
    ../lib/src/osJamMesg.c ^
    ../lib/src/osPiGetCmdQueue.c ^
    ../lib/src/__osSiCreateAccessQueue.c ^
    ../lib/src/__osSiRawStartDma.c ^
    ../lib/src/osVirtualToPhysical.c ^
    ../lib/src/__osSiDeviceBusy.c ^
    ../src/menu/level_select_menu.c ^
    ../lib/src/osViSetEvent.c ^
    ../lib/src/osSetEventMesg.c ^
    ../src/audio/globals_start.c ^
    ../src/audio/globals_end.c ^
    ../lib/src/alBnkfNew.c ^
    ../lib/src/osCreateViManager.c ^
    ../lib/src/__osPiCreateAccessQueue.c ^
    ../lib/src/osViData.c ^
    ../lib/src/osAiGetLength.c ^
    ../lib/src/osViSetMode.c ^
    ../lib/src/osSpTaskYielded.c ^
    ../lib/src/osSetThreadPri.c ^
    ../lib/src/osPiRawReadIo.c ^
    ../lib/src/osPiRawStartDma.c ^
    ../lib/src/osAiSetNextBuffer.c ^
    ../src/audio/effects.c ^
    ../lib/src/__osViSwapContext.c ^
    ../lib/src/__osDevMgrMain.c ^
    ../lib/src/osCreateThread.c ^
    ../lib/src/osGetThreadPri.c ^
    ../lib/src/osSpTaskYield.c ^
    ../lib/src/osSpTaskLoadGo.c ^
    ../lib/src/__osViGetCurrentContext.c ^
    ../lib/src/__osSiRawReadIo.c ^
    ../lib/src/__osSiRawWriteIo.c ^
    ../lib/src/__osSpGetStatus.c ^
    ../lib/src/__osSpSetPc.c ^
    ../lib/src/__osSpDeviceBusy.c ^
    ../lib/src/__osSpRawStartDma.c ^
    ../lib/src/__osAiDeviceBusy.c ^
    ../lib/src/osViTable.c ^
    ../tools/libmio0.c ^
    ../build/us/assets/mario_anim_data.c ^
    ../build/us/assets/demo_data.c

emcc -g4 --source-map-base "http://localhost:8080/" -s ALLOW_MEMORY_GROWTH=1 -o sm64.html sm64.o actors.o levels.o bin.o
